#!/bin/bash
# setup/steps/07-controller.sh — bring the controller up and say what is
# now running, where the UI is, how to reach it from another machine, and
# what each job polls.

STEP_TITLE_controller="bring the controller up"

_jenkins_port() { grep -E '^JENKINS_PORT=' "$J/.env" 2>/dev/null | tail -1 | cut -d= -f2- || true; }

step_controller_check() {
    local okall=1 port; port="$(_jenkins_port)"; port="${port:-8080}"
    doctor_check '.env' '.env'                  || okall=0
    doctor_check 'jenkins_home' 'jenkins_home'  || okall=0
    doctor_check 'port binding' 'port binding'  || true
    local code
    code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "http://127.0.0.1:$port/login" 2>/dev/null || true)"
    if [ "$code" = 200 ] || [ "$code" = 403 ]; then
        check OK "the UI answers on 127.0.0.1:$port (HTTP $code)"
    else
        check MISS "nothing answers on 127.0.0.1:$port — the controller is down"
        okall=0
        todo "start the controller" "pol jenkins up"
    fi
    check OK "admin password: $(secrets_dir)/admin/jenkins_admin_password (generated by pol jenkins up, printed once)"
    check OK "reach it from another machine: ssh -L $port:127.0.0.1:$port <alias>, then http://127.0.0.1:$port — nothing is ever exposed"
    [ "$okall" = 1 ] && state done "controller up, UI on 127.0.0.1:$port" || state todo "controller down"
    [ "$okall" = 1 ]
}

# ci-11a. `pol jenkins up` is unprivileged (it goes through the docker socket,
# which is why step 2 makes the docker-group membership an explicit, named act)
# and has its own verb rather than going through setup-run: it is long-running
# and a caller wants to stream it.
step_controller_json() {
    local port; port="$(_jenkins_port)"; port="${port:-8080}"
    json_explain "The controller is one container. Its UI binds 127.0.0.1:$port ONLY — there is no webhook, no tunnel and no inbound port anywhere in this design. From another machine you reach it by forwarding the port over ssh:

  ssh -L $port:127.0.0.1:$port <alias>    then open http://127.0.0.1:$port

First login is 'admin'; the password is the admin/jenkins_admin_password secret, generated by the first bring-up and printed once.

Four jobs: polari-dev-build polls dev and pushes nothing; polari-release polls main, mints the tag and writes release.json + SHA256SUMS; polari-isle-test runs the throwaway isle stage by stage; polari-publish runs the routes, and a route publishes for real only when its secret is present AND it is named in CI_ROUTES AND the isle test passed for what it would publish."
    local code
    code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "http://127.0.0.1:$port/login" 2>/dev/null || true)"
    json_action up 'Bring the controller up' 0 up \
        "$([ "$code" = 200 ] || [ "$code" = 403 ] && echo 1 || echo 0)" \
        "writes .env if absent, creates jenkins_home/ and pool/, builds the controller image (a few minutes the first time) and starts it on 127.0.0.1:$port. It needs the docker socket, not root." ''
}

step_controller_do() {
    local port; port="$(_jenkins_port)"; port="${port:-8080}"
    explain "The controller is one container. Its UI binds 127.0.0.1:$port ONLY — there is no webhook, no tunnel and no inbound port anywhere in this design. From another machine you reach it by forwarding the port over ssh:

  ssh -L $port:127.0.0.1:$port <alias>    then open http://127.0.0.1:$port

First login is 'admin'; the password is the admin/jenkins_admin_password secret, generated by pol jenkins up and printed once.

Four jobs, and what each does:
  polari-dev-build   polls dev every 10 min — builds the debs and images. Pushes nothing.
  polari-release     polls main every 10 min — mints polari-vYYYY.MM.DD[.N], builds the pool, writes release.json + SHA256SUMS. It pushes the tag only when a github credential is present.
  polari-isle-test   the throwaway isle, stage by stage — it writes the results the release rule reads.
  polari-publish     the routes. DRY_RUN=auto: a route publishes for real only when its secret is present AND it is named in CI_ROUTES AND the isle test passed for what it would publish."
    echo
    step_controller_check || true
    echo
    if ask "bring the controller up?" "Run pol jenkins up now? It writes .env if absent, creates jenkins_home/ and pool/, builds the controller image (a few minutes the first time) and starts it on 127.0.0.1:$port."; then
        if [ -r "$CLI_JENKINS" ]; then act "controller up" -- bash "$CLI_JENKINS" up || true
        else check BAD "polari-cli is not populated — cannot run pol jenkins up"; fi
        PREFLIGHT_JSON=""
    fi
    echo
    step_controller_check || true
}
