#!/bin/bash
# os-security/audit.sh — score every ring on THIS machine. Read-only. pass/fail/skip
# per control with the evidence, a verdict (hardened | partial | open), --json for rows.
#   bash audit.sh [--scenario isle] [--json]
set -u
SC="${OS_SEC_SCENARIO:-}"; JSON=false
while [ $# -gt 0 ]; do case "$1" in --scenario) SC="$2"; shift 2 ;; --json) JSON=true; shift ;; *) shift ;; esac; done
SUDO=""; [ "$(id -u)" = 0 ] || { sudo -n true 2>/dev/null && SUDO="sudo -n"; }
R=(); P=0; F=0; S=0
res() { # ring control status evidence
    R+=("{\"ring\":\"$1\",\"control\":\"$2\",\"status\":\"$3\",\"evidence\":\"$(echo "$4" | sed 's/"/\\"/g' | tr -d '\n' | cut -c1-200)\"}")
    case "$3" in pass) P=$((P+1)); c="\033[0;32mpass\033[0m" ;; fail) F=$((F+1)); c="\033[0;31mFAIL\033[0m" ;; *) S=$((S+1)); c="\033[1;33mskip\033[0m" ;; esac
    $JSON || printf "  %-8s %-34s %b  %s\n" "$1" "$2" "$c" "$4"
}
$JSON || echo "os-security audit · $(hostname) · $(date -Is)${SC:+ · scenario $SC}"
# ---- DAC
if docker info >/dev/null 2>&1; then
    SO=$(docker info --format '{{json .SecurityOptions}}' 2>/dev/null)
    echo "$SO" | grep -q userns && res dac userns-remap pass "$SO" || res dac userns-remap fail "container root = host root ($SO)"
    ROOTS=$(for c in $(docker ps -q); do docker inspect "$c" --format '{{.Name}} user={{.Config.User}} nnp={{.HostConfig.SecurityOpt}}'; done | grep -c 'user= ' || true)
    [ "$ROOTS" = 0 ] && res dac containers-non-root pass "every container declares a user" || res dac containers-non-root fail "$ROOTS container(s) run as root inside"
    PRIV=$(for c in $(docker ps -q); do docker inspect "$c" --format '{{.HostConfig.Privileged}}'; done | grep -c true || true)
    [ "$PRIV" = 0 ] && res dac no-privileged pass "no --privileged" || res dac no-privileged fail "$PRIV privileged container(s)"
    SOCK=$(for c in $(docker ps -q); do docker inspect "$c" --format '{{range .Mounts}}{{.Source}} {{end}}'; done | grep -c docker.sock || true)
    [ "$SOCK" = 0 ] && res dac no-docker-socket-mounts pass "no container mounts docker.sock" || res dac no-docker-socket-mounts fail "$SOCK container(s) mount docker.sock"
    RO=$(for c in $(docker ps -q); do docker inspect "$c" --format '{{.HostConfig.ReadonlyRootfs}}'; done | grep -c false || true)
    [ "$RO" = 0 ] && res dac read-only-rootfs pass "all read-only" || res dac read-only-rootfs fail "$RO container(s) with a writable root filesystem"
else res dac userns-remap skip "docker not reachable"; fi
[ -d /etc/isle-mesh ] && { M=$(stat -c '%a %U:%G' /etc/isle-mesh); case "$M" in 750*|700*) res dac isle-state-perms pass "$M" ;; *) res dac isle-state-perms fail "/etc/isle-mesh is $M (want 750 root:isle-admin)" ;; esac; } || res dac isle-state-perms skip "no /etc/isle-mesh"
G=$(ls /etc/sudoers.d/ 2>/dev/null | grep -c "^polari-" || true); [ "$G" -gt 0 ] && res dac sudo-groups pass "$G polari sudoers group file(s)" || res dac sudo-groups fail "no polari-remote/polari-app sudoers groups (pol deploy grant)"
# ---- MAC
if $SUDO aa-status >/dev/null 2>&1; then
    AAS=$($SUDO aa-status 2>/dev/null)
    echo "$AAS" | grep -q "apparmor module is loaded" && res mac apparmor-loaded pass "$(echo "$AAS" | grep -m1 'profiles are loaded')" || res mac apparmor-loaded fail "module not loaded"
    # how the MAC ring attaches on this route: per container (security_opt) or the node-wide docker-default (swarm)
    ATT=security_opt; MF="$(dirname "$0")/out/${SC:-none}/manifest.json"; [ -f "$MF" ] && ATT=$(python3 -c "import json; print(json.load(open('$MF')).get('mac_attach','security_opt'))" 2>/dev/null || echo security_opt)
    OURS_DD=false; grep -q "generated by os-security/render.py" /etc/apparmor.d/docker-default 2>/dev/null && OURS_DD=true
    N=$(echo "$AAS" | grep -c "isle-app-" || true)
    if [ "$ATT" = docker-default ]; then
        $OURS_DD && echo "$AAS" | grep -q "docker-default" && res mac node-profile pass "docker-default is the os-security union profile (swarm: services cannot carry security_opt)" || res mac node-profile fail "docker-default is docker's stock profile (os-security apply --scenario $SC loads the union)"
    else
        [ "$N" -gt 0 ] && res mac per-app-profiles pass "$N isle-app-* profile(s) loaded" || res mac per-app-profiles fail "no isle-app-* profiles (os-security apply)"
    fi
    C=$(echo "$AAS" | sed -n '/complain mode/,/processes/p' | grep -cE "isle-app-|^ *docker-default" || true); [ "$C" = 0 ] && res mac profiles-enforcing pass "none in complain" || res mac profiles-enforcing fail "$C os-security profile(s) in complain mode (warn-only: expected until each is proven)"
    if docker info >/dev/null 2>&1; then
        GEN=$(for c in $(docker ps -q); do docker inspect "$c" --format '{{.AppArmorProfile}}'; done | grep -c '^docker-default$' || true)
        if [ "$ATT" = docker-default ]; then
            $OURS_DD && res mac containers-per-app-profile pass "$GEN container(s) on the union docker-default (per-service profiles impossible on swarm)" || res mac containers-per-app-profile fail "$GEN container(s) on docker's stock profile"
        else
            [ "$GEN" = 0 ] && res mac containers-per-app-profile pass "no container on the generic profile" || res mac containers-per-app-profile fail "$GEN container(s) on docker-default ($($OURS_DD && echo 'the os-security union — a warn-only baseline until each app carries its own profile' || echo generic))"
        fi
        SEC=$(for c in $(docker ps -q); do docker inspect "$c" --format '{{.HostConfig.SecurityOpt}}'; done | grep -c seccomp || true)
        DSEC=$(docker info --format '{{json .SecurityOptions}}' 2>/dev/null | grep -o 'seccomp,profile=[^"]*')
        if [ "$ATT" = docker-default ]; then case "$DSEC" in *profile=builtin|"") res mac seccomp-per-kind fail "builtin seccomp only (swarm: the daemon's seccomp-profile setting is the lever)" ;; *) res mac seccomp-per-kind pass "daemon seccomp $DSEC" ;; esac
        else [ "$SEC" -gt 0 ] && res mac seccomp-per-kind pass "$SEC container(s) with an explicit seccomp profile" || res mac seccomp-per-kind fail "builtin seccomp only"; fi
    fi
    # what enforcing would break: ALLOWED lines (complain) or DENIED lines (enforce) for our profiles in the last day
    AL=$(python3 "$(dirname "$0")/allowed.py" --since 1d --json 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(sum(g['count'] for g in d['groups']))" 2>/dev/null)
    if [ -n "$AL" ]; then [ "$AL" = 0 ] && res mac no-audit-lines-24h pass "no ALLOWED/DENIED lines for os-security profiles in 24 h" || res mac no-audit-lines-24h fail "$AL access(es) outside the profiles in 24 h (pol security os allowed --rules)"
    else res mac no-audit-lines-24h skip "kernel log not readable (root/adm)"; fi
else res mac apparmor-loaded skip "aa-status needs root"; fi
if command -v virsh >/dev/null 2>&1; then
    U=$($SUDO virsh list --name 2>/dev/null | grep -c . || true)
    if [ "$U" -gt 0 ]; then UN=$(for v in $($SUDO virsh list --name); do $SUDO virsh dominfo "$v" | grep -q "Security model: apparmor" || echo "$v"; done | wc -w); [ "$UN" = 0 ] && res mac svirt-guests pass "$U guest(s) under libvirt AppArmor" || res mac svirt-guests fail "$UN guest(s) unconfined"; else res mac svirt-guests skip "no running guests"; fi
fi
# ---- NETWORK
DU=$($SUDO iptables -S DOCKER-USER 2>/dev/null | grep -c "os-security" || true); [ "$DU" -gt 0 ] && res network docker-user-rules pass "$DU rule(s)" || res network docker-user-rules fail "DOCKER-USER carries no os-security rules (containers can reach host services)"
UF=$($SUDO ufw status 2>/dev/null | head -1); case "$UF" in *active*) [ "${UF#*: }" = active ] && res network ufw pass "$UF" || res network ufw fail "$UF" ;; *) res network ufw skip "ufw not readable" ;; esac
SSHALL=$(ss -ltn 2>/dev/null | awk '$4 ~ /(^0\.0\.0\.0|^\*|^\[::\]):22$/' | wc -l); [ "$SSHALL" = 0 ] && res network ssh-not-on-all-interfaces pass "sshd bound to specific addresses" || res network ssh-not-on-all-interfaces fail "sshd listens on all interfaces (ufw/sshd ListenAddress)"
TCP=$(ss -ltn 2>/dev/null | grep -cE ':2375 |:2376 ' || true); [ "$TCP" = 0 ] && res network no-docker-tcp pass "no docker TCP socket" || res network no-docker-tcp fail "docker listens on TCP"
if docker info >/dev/null 2>&1 && docker info --format '{{.Swarm.LocalNodeState}}' | grep -q active; then
    ENC=$(docker network ls --filter driver=overlay -q | xargs -r docker network inspect --format '{{.Name}} {{index .Options "encrypted"}}' 2>/dev/null | grep -v ingress | grep -vc 'true' || true)
    [ "$ENC" = 0 ] && res network overlay-encrypted pass "every overlay encrypted" || res network overlay-encrypted fail "$ENC overlay network(s) unencrypted"
fi
# ---- PHYSICAL (his ask 2026-09-13: Secure Boot and disk encryption as OS-level controls against someone holding the machine)
if [ -d /sys/firmware/efi ]; then
    SB=$(command -v mokutil >/dev/null 2>&1 && mokutil --sb-state 2>/dev/null | head -1); [ -n "$SB" ] || SB=$(f=$(ls /sys/firmware/efi/efivars/SecureBoot-* 2>/dev/null | head -1); [ -n "$f" ] && { [ "$(od -An -tu1 -j4 -N1 "$f" 2>/dev/null | tr -d ' ')" = 1 ] && echo "SecureBoot enabled" || echo "SecureBoot disabled"; })
    case "$SB" in *enabled*) res physical secure-boot pass "$SB (Ubuntu's signed boot chain)" ;; *disabled*) res physical secure-boot fail "$SB — a tampered boot loader/kernel would start (ISO plan D6: off only deliberately, with a written reason)" ;; *) res physical secure-boot skip "state not readable (mokutil / efivars)" ;; esac
else res physical secure-boot skip "legacy BIOS boot: Secure Boot does not exist here"; fi
CRYPT=$(lsblk -rno TYPE 2>/dev/null | grep -c '^crypt$' || true); ROOTSRC=$(findmnt -no SOURCE / 2>/dev/null)
if [ "$CRYPT" -gt 0 ]; then res physical disk-encryption pass "$CRYPT encrypted volume(s) (LUKS); root on $ROOTSRC"
else res physical disk-encryption fail "no encrypted volume: the drive is readable in another machine (an option, off by default; never on headless — ISO plan D8)"; fi
# ---- SSH (his ask 2026-09-13: track ssh capabilities across Polari devices as a security vector)
if ss -ltn 2>/dev/null | grep -qE ':22$|:22 '; then
    SSHT=$($SUDO sshd -T 2>/dev/null)
    if [ -n "$SSHT" ]; then
        PA=$(echo "$SSHT" | awk '/^passwordauthentication/ {print $2}'); PR=$(echo "$SSHT" | awk '/^permitrootlogin/ {print $2}'); KI=$(echo "$SSHT" | awk '/^kbdinteractiveauthentication/ {print $2}')
        [ "$PA" = no ] && [ "$KI" != yes ] && res ssh key-only-login pass "password and keyboard-interactive authentication off" || res ssh key-only-login fail "PasswordAuthentication=$PA KbdInteractive=$KI — a guessable password is the vector; keys only (sshd_config: PasswordAuthentication no)"
        [ "$PR" = no ] && res ssh no-root-login pass "PermitRootLogin no" || res ssh no-root-login fail "PermitRootLogin=$PR — log in as a person and sudo (sshd_config: PermitRootLogin no)"
        # his ruling 2026-09-14: root over ssh must not exist at all (with a key included); what exists is PERMISSION
        # GROUPS allowed over ssh, each with a scoped sudo command set — never a blanket NOPASSWD: ALL
        AG=$(echo "$SSHT" | awk '/^allowgroups/ {$1=""; print}' | xargs)
        [ -n "$AG" ] && res ssh ssh-groups pass "AllowGroups: $AG" || res ssh ssh-groups fail "no AllowGroups — every account with a key may log in; name the permission groups allowed over ssh (sshd_config: AllowGroups polari-ops polari-dev)"
        BLANKET=$(grep -rhsE '^[^#]*ALL[[:space:]]*=[[:space:]]*\(ALL(:ALL)?\)[[:space:]]*(NOPASSWD:[[:space:]]*)?ALL' /etc/sudoers /etc/sudoers.d 2>/dev/null | grep -vE '^(root|%admin|%sudo)[[:space:]]' | xargs -0 echo | head -c 300)
        [ -z "$BLANKET" ] && res ssh sudo-scoped pass "no account or group beyond root/admin/sudo holds a blanket ALL" || res ssh sudo-scoped fail "blanket sudo: $BLANKET — give each ssh group its own command list (/etc/sudoers.d/polari-<group>: %polari-ops ALL=(root) /usr/bin/pol, ...)"
    else res ssh key-only-login skip "sshd -T needs root"; res ssh no-root-login skip "sshd -T needs root"; res ssh ssh-groups skip "sshd -T needs root"; res ssh sudo-scoped skip "reading sudoers needs root"; fi
    AK=$(for h in /root /home/*; do $SUDO cat "$h/.ssh/authorized_keys" 2>/dev/null | grep -cvE '^\s*(#|$)'; done | awk '{s+=$1} END {print s+0}')
    WEAK=$(for h in /root /home/*; do $SUDO cat "$h/.ssh/authorized_keys" 2>/dev/null | grep -vE '^\s*(#|$)' | awk '{print $1}'; done | grep -cE '^(ssh-rsa|ssh-dss)$' || true)
    [ "$WEAK" = 0 ] && res ssh authorized-key-types pass "$AK authorized key(s), all ed25519/ecdsa" || res ssh authorized-key-types fail "$WEAK rsa/dss key(s) of $AK — prefer ed25519"
    F2B=$(systemctl is-active fail2ban 2>/dev/null); [ "$F2B" = active ] && res ssh brute-force-guard pass "fail2ban active" || res ssh brute-force-guard fail "no fail2ban / rate limit on sshd (ufw limit 22 or fail2ban)"
    FL=$($SUDO journalctl -u ssh -u sshd --since '24 hours ago' --no-pager 2>/dev/null | grep -c 'Failed password\|Invalid user' || true)
    [ "${FL:-0}" -lt 20 ] && res ssh failed-logins-24h pass "$FL failed login(s) in 24 h" || res ssh failed-logins-24h fail "$FL failed login(s) in 24 h — someone is knocking"
else res ssh sshd-listening skip "no sshd listening: nobody can ssh in (nor can pol deploy)"; fi
# ---- CERTS (his ask 2026-09-13: expired certificates must be noticed; auto-renew must be on)
if ss -ltn 2>/dev/null | grep -qE ':443 '; then
    END=$(echo | timeout 6 openssl s_client -connect 127.0.0.1:443 -servername localhost 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)
    if [ -n "$END" ]; then D=$(( ( $(date -d "$END" +%s) - $(date +%s) ) / 86400 ))
        if [ "$D" -lt 0 ]; then res certs edge-cert fail "the edge certificate EXPIRED ${D#-} day(s) ago ($END) — pol cert renew"
        elif [ "$D" -lt 14 ]; then res certs edge-cert fail "the edge certificate expires in $D day(s) ($END) — pol cert renew"
        else res certs edge-cert pass "$D day(s) left ($END)"; fi
    else res certs edge-cert skip "443 answers but no certificate could be read"; fi
else res certs edge-cert skip "nothing listens on 443 here"; fi
AR=$( { crontab -l 2>/dev/null; cat /etc/cron.d/* 2>/dev/null; } | grep -c "renew.sh" || true); SYSAR=$(systemctl list-timers --all 2>/dev/null | grep -ciE "certbot|renew" || true)
[ "$AR" -gt 0 ] || [ "$SYSAR" -gt 0 ] && res certs auto-renew pass "renewal scheduled ($AR cron entr(y|ies), $SYSAR timer(s))" || res certs auto-renew fail "no renewal scheduled: certificates will expire silently — pol cert auto-renew install"
# ---- HOST
for k in kernel.kptr_restrict=2 kernel.dmesg_restrict=1 kernel.unprivileged_bpf_disabled=1 fs.protected_symlinks=1 fs.protected_hardlinks=1; do
    v=$(sysctl -n "${k%=*}" 2>/dev/null); { [ "$v" = "${k#*=}" ] || { [ "${k%=*}" = kernel.unprivileged_bpf_disabled ] && [ "${v:-0}" -ge 1 ]; }; } && res host "sysctl ${k%=*}" pass "$v" || res host "sysctl ${k%=*}" fail "is ${v:-unset}, want ${k#*=}"
done
command -v auditctl >/dev/null 2>&1 && { $SUDO auditctl -l 2>/dev/null | grep -q isle-state && res host auditd-rules pass "isle rules loaded" || res host auditd-rules fail "auditd present, isle rules not loaded"; } || res host auditd-rules fail "auditd not installed"
[ -f /etc/apt/apt.conf.d/20auto-upgrades ] && grep -q '"1"' /etc/apt/apt.conf.d/20auto-upgrades && res host unattended-upgrades pass "enabled" || res host unattended-upgrades fail "not enabled"
# ---- verdict
if [ "$F" = 0 ]; then V=hardened; elif [ "$P" -gt "$F" ]; then V=partial; else V=open; fi
if $JSON; then printf '{"host":"%s","scenario":"%s","verdict":"%s","pass":%d,"fail":%d,"skip":%d,"controls":[%s]}\n' "$(hostname)" "$SC" "$V" "$P" "$F" "$S" "$(IFS=,; echo "${R[*]}")"
else echo; echo "  verdict: $V   ($P pass, $F fail, $S skip)"; fi
[ "$V" = hardened ]
